### ISSUE TITLE
Installation and using?

### ISSUE THREAD

**Issue by rajlaksh** [eagletmt/comic_walker#4]
How to Install it correctly and Use it correctly?

Windows XP SP3
Dev Tool is install in C:\DevKit
Ruby install in c:/Ruby193/

$ gem install comic_walker
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing comic_walker:
        ERROR: Failed to build gem native extension.

        c:/Ruby193/bin/ruby.exe extconf.rb
checking for Ruby version >= 1.8.5... yes
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=c:/Ruby193/bin/ruby
c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to genera
te an executable file. (RuntimeError)
You have to install development tools first.
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:506:in `try_cpp'
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:931:in `block in have_header'
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postp
one'
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
        from c:/Ruby193/lib/ruby/1.9.1/mkmf.rb:930:in `have_header'
        from extconf.rb:212:in `<main>'

Gem files will remain installed in c:/Ruby193/lib/ruby/gems/1.9.1/gems/rmagick-2
.13.4 for inspection.
Results logged to c:/Ruby193/lib/ruby/gems/1.9.1/gems/rmagick-2.13.4/ext/RMagick
/gem_make.out

ON CENTOS 6.5

Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
ERROR:  Error installing comic_walker:
        ERROR: Failed to build gem native extension.

/usr/bin/ruby extconf.rb
extconf.rb:153: undefined (?...) sequence: /^Version: ImageMagick\s+(?<Version>\d+\.\d+\.\d+\-\d+)\s+(?<Unknown>\S+)\s+(?<Arch>\S+)\s+(?<Date>\S+)/

Gem files will remain installed in /usr/lib/ruby/gems/1.8/gems/rmagick-2.13.4 for inspection.
Results logged to /usr/lib/ruby/gems/1.8/gems/rmagick-2.13.4/ext/RMagick/gem_make.out

**Comment by eagletmt** [comment]
## On Windows
I'm not sure but did you install ImageMagick?
comic_walker requires it.

## On CentOS
Your Ruby version looks too old. Ruby 1.8.x isn't supported any more.
Could you install newer Ruby, at least Ruby 2.0.0?

**Comment by rajlaksh** [comment]
I've ImageMagick installed.

Ruby is 1.9.x.

I tried to install it on Linux too. Didn't works :(
