### ISSUE TITLE
Are you willing to update?

### ISSUE THREAD

**Issue by ker0r0** [eagletmt/comic_walker#5]
I'd like you to modify this script for Jump+. Thanks.

**Comment by eagletmt** [comment]
Actually Jump plus is using the same system, but it actually has a serious problem once (that I reported).
If I could confirm it's already fixed, I'm willing to support it.

**Comment by ker0r0** [comment]
I'm looking forward to good news from you. Thank you for your comment.

**Comment by kavin-90** [comment]
@eagletmt any news? 

because https://bitbucket.org/gvim/eaglemt-comicwalker/overview work on Jump+ before 2016 but now that repo has been removed and that Jump+ code does not working.

**Comment by tpk2** [comment]
@eagletmt 

What is the serious problem for Jump+? Maybe there is a fix?

**Comment by kavin-90** [comment]
@eagletmt any update?

**Comment by kavin-90** [comment]
Jump + removed `https://dpe.store007-access-company.com/api4js/v1/c/#{cid}/li` for license key that is what biggest problem. 2nd `https://dpe.store007-access-company.com/api4js/v1/c/#{cid}/lo` routes give license key but its quite Big Key.
